// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/documents.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document representa un documento en el sistema
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ContentB64    string                 `protobuf:"bytes,7,opt,name=content_b64,json=contentB64,proto3" json:"content_b64,omitempty"`
	CoverImage    string                 `protobuf:"bytes,8,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_documents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_documents_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Document) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Document) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Document) GetContentB64() string {
	if x != nil {
		return x.ContentB64
	}
	return ""
}

func (x *Document) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

// Request para obtener todos los documentos
type GetAllDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDocumentsRequest) Reset() {
	*x = GetAllDocumentsRequest{}
	mi := &file_proto_documents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDocumentsRequest) ProtoMessage() {}

func (x *GetAllDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDocumentsRequest.ProtoReflect.Descriptor instead.
func (*GetAllDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_documents_proto_rawDescGZIP(), []int{1}
}

// Response con lista de documentos
type GetAllDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDocumentsResponse) Reset() {
	*x = GetAllDocumentsResponse{}
	mi := &file_proto_documents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDocumentsResponse) ProtoMessage() {}

func (x *GetAllDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDocumentsResponse.ProtoReflect.Descriptor instead.
func (*GetAllDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_documents_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *GetAllDocumentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Request para obtener un documento por ID
type GetDocumentByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentByIdRequest) Reset() {
	*x = GetDocumentByIdRequest{}
	mi := &file_proto_documents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentByIdRequest) ProtoMessage() {}

func (x *GetDocumentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentByIdRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_documents_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response con un documento
type GetDocumentByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentByIdResponse) Reset() {
	*x = GetDocumentByIdResponse{}
	mi := &file_proto_documents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentByIdResponse) ProtoMessage() {}

func (x *GetDocumentByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentByIdResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_documents_proto_rawDescGZIP(), []int{4}
}

func (x *GetDocumentByIdResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

var File_proto_documents_proto protoreflect.FileDescriptor

const file_proto_documents_proto_rawDesc = "" +
	"\n" +
	"\x15proto/documents.proto\x12\tdocuments\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vcontent_b64\x18\a \x01(\tR\n" +
	"contentB64\x12\x1f\n" +
	"\vcover_image\x18\b \x01(\tR\n" +
	"coverImage\"\x18\n" +
	"\x16GetAllDocumentsRequest\"b\n" +
	"\x17GetAllDocumentsResponse\x121\n" +
	"\tdocuments\x18\x01 \x03(\v2\x13.documents.DocumentR\tdocuments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"(\n" +
	"\x16GetDocumentByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x17GetDocumentByIdResponse\x12/\n" +
	"\bdocument\x18\x01 \x01(\v2\x13.documents.DocumentR\bdocument2\xc5\x01\n" +
	"\x0fDocumentService\x12X\n" +
	"\x0fGetAllDocuments\x12!.documents.GetAllDocumentsRequest\x1a\".documents.GetAllDocumentsResponse\x12X\n" +
	"\x0fGetDocumentById\x12!.documents.GetDocumentByIdRequest\x1a\".documents.GetDocumentByIdResponseB!Z\x1fmarkitos-it-svc-documents/protob\x06proto3"

var (
	file_proto_documents_proto_rawDescOnce sync.Once
	file_proto_documents_proto_rawDescData []byte
)

func file_proto_documents_proto_rawDescGZIP() []byte {
	file_proto_documents_proto_rawDescOnce.Do(func() {
		file_proto_documents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_documents_proto_rawDesc), len(file_proto_documents_proto_rawDesc)))
	})
	return file_proto_documents_proto_rawDescData
}

var file_proto_documents_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_documents_proto_goTypes = []any{
	(*Document)(nil),                // 0: documents.Document
	(*GetAllDocumentsRequest)(nil),  // 1: documents.GetAllDocumentsRequest
	(*GetAllDocumentsResponse)(nil), // 2: documents.GetAllDocumentsResponse
	(*GetDocumentByIdRequest)(nil),  // 3: documents.GetDocumentByIdRequest
	(*GetDocumentByIdResponse)(nil), // 4: documents.GetDocumentByIdResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_proto_documents_proto_depIdxs = []int32{
	5, // 0: documents.Document.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: documents.GetAllDocumentsResponse.documents:type_name -> documents.Document
	0, // 2: documents.GetDocumentByIdResponse.document:type_name -> documents.Document
	1, // 3: documents.DocumentService.GetAllDocuments:input_type -> documents.GetAllDocumentsRequest
	3, // 4: documents.DocumentService.GetDocumentById:input_type -> documents.GetDocumentByIdRequest
	2, // 5: documents.DocumentService.GetAllDocuments:output_type -> documents.GetAllDocumentsResponse
	4, // 6: documents.DocumentService.GetDocumentById:output_type -> documents.GetDocumentByIdResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_documents_proto_init() }
func file_proto_documents_proto_init() {
	if File_proto_documents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_documents_proto_rawDesc), len(file_proto_documents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_documents_proto_goTypes,
		DependencyIndexes: file_proto_documents_proto_depIdxs,
		MessageInfos:      file_proto_documents_proto_msgTypes,
	}.Build()
	File_proto_documents_proto = out.File
	file_proto_documents_proto_goTypes = nil
	file_proto_documents_proto_depIdxs = nil
}
